/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author santi
 */
public class CompraExitosa extends javax.swing.JFrame {

    /**
     * Creates new form CompraExitosa
     */
    public CompraExitosa() {
        this.setTitle("Aterrizar.com");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSeguirBuscando = new javax.swing.JButton();
        asiento = new javax.swing.JLabel();
        nombreAsiento = new javax.swing.JLabel();
        compraExitosa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonSeguirBuscando.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonSeguirBuscando.setText("Seguir Buscando");
        botonSeguirBuscando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirBuscandoActionPerformed(evt);
            }
        });

        asiento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        asiento.setText("El asiento");

        nombreAsiento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nombreAsiento.setText("XXXXXX");

        compraExitosa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        compraExitosa.setText("ha sido comprado exitosamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(asiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreAsiento)
                        .addGap(18, 18, 18)
                        .addComponent(compraExitosa))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonSeguirBuscando)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asiento)
                    .addComponent(nombreAsiento)
                    .addComponent(compraExitosa))
                .addGap(18, 18, 18)
                .addComponent(botonSeguirBuscando)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeguirBuscandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirBuscandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirBuscandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraExitosa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asiento;
    private javax.swing.JButton botonSeguirBuscando;
    private javax.swing.JLabel compraExitosa;
    private javax.swing.JLabel nombreAsiento;
    // End of variables declaration//GEN-END:variables
}
