//GEN-LINE:variables
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import Controladores.ControladorComprasReservas;
import AterrizarDummy.AterrizarDummy;

public class ReservasCompras extends javax.swing.JFrame {
    private ControladorComprasReservas controlador;
    
    public ReservasCompras(){
        this.setTitle("Aterrizar.com");
        this.setResizable(false);
        initComponents();
    }
    
    public ReservasCompras(String tipoVentana) {
        this.setTitle("Aterrizar.com");
        this.setResizable(false);
        controlador = crearControladorComprasReservas(tipoVentana);
        initComponents();
        setearNombreVentana(tipoVentana);
        setearNombreUsuario();
        agregarFuncionalidadBotonCierra();
        rellenarTabla();
    }
    
    public void rellenarTabla(){
        eliminarCeldasTabla();
        controlador.getModelo().obtenerAsientosUsuario().forEach(as -> {
            String fechaSalida = as.getFechaSalida().representacionEnIso();
            String codigoAsiento = as.getAsiento().getCodigo().getCodigo();
            String codigoVuelo = codigoAsiento.split("-")[0];
            String numeroVuelo = codigoAsiento.split("-")[1];
            String precio = Double.toString(as.getAsiento().getPrecio().getPrecioAsiento());
            String aerolinea = AterrizarDummy.getPagina().obtenerAerolineaAsiento(codigoAsiento);
            rellenarFilaTabla(fechaSalida,aerolinea,codigoVuelo,numeroVuelo,precio);
        });
    }
    
    public void setearNombreVentana(String tipoVentana){
        if(tipoVentana.equals("compras")){
            nombreLabelVentana.setText("Compras de: ");
        }
        else{
            nombreLabelVentana.setText("Reservas de: ");
        }
    }
    
    public void agregarFuncionalidadBotonCierra(){
        botonCerrar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
               cerrarVentana();
            }
        });
    }
    
    public void cerrarVentana(){
        this.setVisible(false);
        this.dispose();
    }
    
    public void eliminarCeldasTabla(){
        DefaultTableModel tb = (DefaultTableModel) infoTablaUsuario.getModel();
        int a = infoTablaUsuario.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
    }
    
    private void setearNombreUsuario(){
        this.nombreUsuario.setText(controlador.getModelo().getNombreUsuario());
    }
    
    private ControladorComprasReservas crearControladorComprasReservas(String tipoVentana){
        return new ControladorComprasReservas(tipoVentana);
    }
    
    public void rellenarFilaTabla(String fechaSalida, String aerolinea, String codigoVuelo, String nroAsiento, String precio){
        DefaultTableModel modelo = (DefaultTableModel) infoTablaUsuario.getModel();
        Object[] filaAgregar = {fechaSalida,aerolinea,codigoVuelo,nroAsiento,precio};
        modelo.addRow(filaAgregar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        nombreLabelVentana = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTablaUsuario = new javax.swing.JTable();
        botonCerrar = new javax.swing.JButton();
        nombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreLabelVentana.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nombreLabelVentana.setText("Reservas de ");

        infoTablaUsuario = new javax.swing.JTable(){
            public boolean isCellEditable(int i, int n){
                return false;
            }
        };
        infoTablaUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        infoTablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salida", "Aerolinea", "Vuelo", "Asiento", "Precio"
            }
        ));
        infoTablaUsuario.setFocusable(false);
        infoTablaUsuario.getTableHeader().setResizingAllowed(false);
        infoTablaUsuario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(infoTablaUsuario);

        botonCerrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonCerrar.setText("Cerrar");

        nombreUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nombreUsuario.setText("XXXXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreLabelVentana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreUsuario))
                    .addComponent(botonCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabelVentana)
                    .addComponent(nombreUsuario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonCerrar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservasCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonCerrar;
    private javax.swing.JTable infoTablaUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabelVentana;
    private javax.swing.JLabel nombreUsuario;
    // End of variables declaration                   
}
