/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author santi
 */
public class Sobrereservar extends javax.swing.JFrame {

    /**
     * Creates new form Sobrereservar
     */
    public Sobrereservar() {
        this.setTitle("Aterrizar.com");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSeguirBuscando = new javax.swing.JButton();
        asiento = new javax.swing.JLabel();
        nombreAsiento = new javax.swing.JLabel();
        yaEstaReservado = new javax.swing.JLabel();
        sobrereservar = new javax.swing.JButton();
        queDeseaHacer = new javax.swing.JLabel();
        botonSeguirBuscandoo = new javax.swing.JButton();

        botonSeguirBuscando.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonSeguirBuscando.setText("Seguir Buscando");
        botonSeguirBuscando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirBuscandoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        asiento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        asiento.setText("El asiento");

        nombreAsiento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nombreAsiento.setText("XXXXXX");

        yaEstaReservado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        yaEstaReservado.setText("ya se encuentra reservado");

        sobrereservar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sobrereservar.setText("Sobrereservar");

        queDeseaHacer.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        queDeseaHacer.setText("¿Qué desea hacer?");

        botonSeguirBuscandoo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonSeguirBuscandoo.setText("Seguir Buscando");
        botonSeguirBuscandoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirBuscandooActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sobrereservar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(botonSeguirBuscandoo))
                    .addComponent(queDeseaHacer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreAsiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yaEstaReservado)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asiento)
                    .addComponent(nombreAsiento)
                    .addComponent(yaEstaReservado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queDeseaHacer)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrereservar)
                    .addComponent(botonSeguirBuscandoo))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeguirBuscandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirBuscandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirBuscandoActionPerformed

    private void botonSeguirBuscandooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirBuscandooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSeguirBuscandooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobrereservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobrereservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobrereservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobrereservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobrereservar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asiento;
    private javax.swing.JButton botonSeguirBuscando;
    private javax.swing.JButton botonSeguirBuscandoo;
    private javax.swing.JLabel nombreAsiento;
    private javax.swing.JLabel queDeseaHacer;
    private javax.swing.JButton sobrereservar;
    private javax.swing.JLabel yaEstaReservado;
    // End of variables declaration//GEN-END:variables
}
